//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int Numero_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public string Descripcion_Servicios { get; set; }
        public Nullable<int> Cantidad_Servicios { get; set; }
        public Nullable<double> Precio_Unitario { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<int> Impuestos { get; set; }
        public Nullable<double> Total { get; set; }
        public string DNI { get; set; }
    
        public virtual Usuario_Normal Usuario_Normal { get; set; }
    }
}
