//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Actividad
    {
        public string DNI { get; set; }
        public int Id_Actividad { get; set; }
        public Nullable<byte> Valoracion { get; set; }
        public Nullable<System.DateTime> Fecha_Valoracion { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Usuario_Normal Usuario_Normal { get; set; }
    }
}
